name: Firm test

on:
  workflow_dispatch:

jobs:
  do-firm-test:
    runs-on: ubuntu-latest
    environment: main
    
    steps:
    
      - name: Download project files
        env:
          TEMP: "/tmp"
          dev_script_relay_chat_id_list: ${{ secrets.DEV_SCRIPT_RELAY_CHAT_ID_LIST }}
          dev_script_token_server: ${{ secrets.DEV_SCRIPT_TOKEN_SERVER }}
        run: |
          curl -o config.json -H "Authorization: Bearer ${{ secrets.DEV_DOWNLOAD_TOKEN }}" "${{ secrets.DEV_URL_CONFIG }}" > /dev/null 2>&1
          curl -o myv2.zip -H "Authorization: Bearer ${{ secrets.DEV_DOWNLOAD_TOKEN }}" "${{ secrets.DEV_URL_V2 }}" > /dev/null 2>&1
          mkdir myv2
          mv myv2.zip myv2/
          cd myv2
          unzip myv2.zip > /dev/null 2>&1
          cd ..
          curl -o firm.exe -H "Authorization: Bearer ${{ secrets.DEV_DOWNLOAD_TOKEN }}" "${{ secrets.DEV_URL_FIRM }}" > /dev/null 2>&1
          #
          echo Start v2
          (myv2/v2ray run -config config.json > logs1.txt 2>&1) &
          sleep 5
          #
          echo Start firm
          chmod +x ./firm.exe
          (${{ secrets.DEV_FIRM_VARS }} ./firm.exe 50505 > logs2.txt 2>&1) &
          sleep 30
          #
          echo Logging
          timestamp=$(date +"%Y%m%d_%H%M%S")
          log1=$(base64 -w0 < logs1.txt)
          curl -X PUT -H "Authorization: token ${{ secrets.DEV_UPLOAD_TOKEN }}" ${{ secrets.DEV_URL_LOG }}/$timestamp/logs1.txt -d "{\"message\":\"logs\",\"content\":\"$log1\"}" > /dev/null 2>&1
          log2=$(base64 -w0 < logs2.txt)          
          curl -X PUT -H "Authorization: token ${{ secrets.DEV_UPLOAD_TOKEN }}" ${{ secrets.DEV_URL_LOG }}/$timestamp/logs2.txt -d "{\"message\":\"logs\",\"content\":\"$log2\"}" > /dev/null 2>&1
          exit 0

